### ISSUE TITLE
Proyecto Final de Linux

### ISSUE THREAD

**Issue by MARIA2M** [MARIA2M/decont#1]
Hola Tomás,

Anoche quise terminar el proyecto de clase y en principio creo que está hecho a falta de si consideras que me he dejado algo o tengo que cambiar algo. Tuve una serie de problemas a la hora de indexar que solo pude solucionar apagando y encendiendo el ordenador porque debía de estar relacionado con la memoria ram por lo que estuve leyendo.

Starting to generate Genome files
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Tuve también algunos errores pequeños que no reconocían partes de los bucles por algún motivo, pero creo que ya todo debería funcionar. Terminé tarde, pero el hecho de qudarme por la noche fue más por tener la semana ocupada y tener que ir a Málaga este fin de semana por temas médicos desde jueves. Prefería tenerlo hecho cuanto antes para poder corregir las cosas con tiempo. 

Cuando puedas echarle un vistazo avisame, por favor.

**Comment by tdido** [comment]
Hola María.

Tu solución está muy bien, así que cierro esta issue para indicar que terminaste el trabajo. Te dejo dos comentarios menores para que los tengas como referencia futura, pero que no afectan a tu calificación:

1) En "download.sh", podrías poner el `if` para descomprimir dentro del `then` del primer `if`, luego de la descarga, y ahorrarte unas cuantas líneas de código repetitivas.

2) En "merge.sh", para hacer que el script sea bien genérico podrías usar `$3*.fastq.gz`, de manera de tomar cualquier archivo que comience con el sample id y termine con fastq.gz.

Cuando todos hayan finalizado subiré también una solución para que tengan como referencia.
